update: add issues detection for `dart format .` and `flutter gen-l10n`
- add Check Localization Files
- add Run Dart Format Check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,7 +16,32 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
       - name: Generate Localization Files
-        run: flutter gen-l10n
+        id: gen_l10n
+        run: |
+          # Run the command to generate localization files and capture the output
+          output=$(flutter gen-l10n)
+          echo "$output"
+          
+          # Check if there are untranslated messages in the output
+          if echo "$output" | grep -q "untranslated message"; then
+            echo "::error file=lib/l10n/l10n.yaml::Error: Untranslated messages detected in your localization files."
+            echo "::error::There are untranslated messages in the following languages:"
+            echo "$output" | grep "untranslated message"
+            echo "::error::Please ensure that all translations are provided in the respective .arb files."
+            exit 1
+          fi
+      - name: Check Localization Files
+        run: |
+          git diff --exit-code lib/l10n/ || (
+            echo "Localization files are outdated. Run 'flutter gen-l10n' and commit changes.";
+            exit 1;
+          )
+      - name: Run Dart Format Check
+        run: |
+          dart format . --set-exit-if-changed || (
+            echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
+            exit 1;
+          )
       - name: Run Flutter Analyze
         run: flutter analyze
       - name: Run tests
